steps:
# - name: 'gcr.io/cloud-builders/npm'
#   args: ['install']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'lint']

# - name: 'gcr.io/cloud-builders/npm'
#   args: ['run', 'e2e']
 
- name: 'gcr.io/$PROJECT_ID/envsubst'
  args: ['<', './deployment.yaml']
  env:
  - 'PROJECT_ID=$PROJECT_ID'
  - 'REVISION_ID=$REVISION_ID'

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/flight-status:$REVISION_ID', '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/flight-status:$REVISION_ID']

- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply', '-f', './deployment.yaml']
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-east1-d'
  - 'CLOUDSDK_CONTAINER_CLUSTER=flight-status-cluster'